<script setup>
import { Link, useForm } from "@inertiajs/vue3";
import { ref } from 'vue';
import Editor from '@tinymce/tinymce-vue';
let props = defineProps( {
    settings: Object
} );
let currentTab = ref( 'paystack' );

const form = useForm( {
    bank_transfer: {
        transfer_details: props.settings?.bank_transfer.transfer_details ?? `<h4>Equilog Training & Consultancy</h4><ul class='list-unstyled'><li>Access Bank: <strong>0051030986</strong></li><li>Covenant Microfinance: <strong>0520058031</strong></li></ul>`,
        manual_payment_instructions: props.settings?.bank_transfer.manual_payment_instructions ?? ` <p>You can make payment via bank deposit or mobile transer directly to any of the bank account displayed in the invoice <strong>using the generated invoice code</strong> as narration. This makes it easier for the administrator to track the payment</p><p>You are to then click on the "Upload Payment Evidence" button below to upload evidence of successful payment. Proof of payment might consist of the bank teller used in making deposit or the receipt generated by your bank application and <strong>not your SMS debit notification.</strong> </p><p>Your invoice status chould change on successful verification or contact support if don't get anyresponse within the next 6 hours.</p>`
    },
    paystack: {
        status: props.settings?.paystack.status ?? false,
        live: props.settings?.paystack.live ?? false,
        pk_test: props.settings?.paystack.test_pk ?? 'pk_test_a509cf0b75f217f6e0adf29ab8cf622d86a70544',
        sk_test: props.settings?.paystack.sk_test ?? 'sk_test_1c22c679496097ff2a4eaffc8cd24c95ff27bab1',
        pk_live: props.settings?.paystack.pk_live ?? '',
        sk_live: props.settings?.paystack.sk_live ?? '',
    }
} )

let handleSave = () => form.post( route( 'admin.site-settings.save', [ 'payment' ] ) );

</script>
<template>
    <div>
        <h5 class="card-title mb-3">Payment Option</h5>
        <ul class="nav nav-pills nav-tabs-custom small mb-4">
            <li class="nav-item">
                <button class="nav-link bg-transparent" :class="{ 'active': currentTab == 'bank' }"
                    @click.prevent="currentTab = 'bank'">BANK TRANSFER</button>
            </li>
            <li class="nav-item">
                <button @click.prevent="currentTab = 'paystack'" class="nav-link bg-transparent"
                    :class="{ 'active': currentTab != 'bank' }" href="#">PAYSTACK PAYMENT GATEWAY</button>
            </li>
        </ul>
        <div class="mb-3" v-if="currentTab == 'bank'">
            <div class="form-group mb-5">
                <h5>Bank Accounts Information</h5>
                <editor v-model="form.bank_transfer.transfer_details"
                    api-key="xi62uvac03b7vuqqfj6f3lr8x2z6vkd4048al3e3m9hoouny" :init="{
                        height: '200',
                        menubar: false,
                    }" class="w-100 form-control"></editor>
            </div>
            <div class="form-group mb-3">
                <h5>Instructions on manual payment</h5>
                <editor v-model="form.bank_transfer.manual_payment_instructions"
                    api-key="xi62uvac03b7vuqqfj6f3lr8x2z6vkd4048al3e3m9hoouny" :init="{
                        height: '200',
                        menubar: false,
                    }" class="w-100 form-control"></editor>
            </div>

        </div>
        <div class="mb-3 row" v-if="currentTab == 'paystack'">
            <div class="col-md-6">
                <label>Use Paystack Integration</label>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="paystack_status" v-model="form.paystack.status">
                    <label class="form-check-label" for="paystack_status">Yes</label>
                </div>
            </div>
            <div class="col-md-6" v-if="form.paystack.status">
                <label>API Key Mode</label>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="paystack_mode" v-model="form.paystack.live">
                    <label class="form-check-label" for="paystack_mode">Live</label>
                </div>
            </div>
            <template v-if="form.paystack.status">
                <div class="col-12 mt-3">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" v-model="form.paystack.sk_test">
                        <label>Test Secret Key</label>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" v-model="form.paystack.pk_test">
                        <label>Test Public Key</label>
                    </div>
                </div>
                <hr class="col-12">
                <div class="col-12">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" v-model="form.paystack.sk_live">
                        <label>Live Secret Key</label>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-floating">
                        <input type="text" class="form-control" v-model="form.paystack.pk_live">
                        <label>Live Public Key</label>
                    </div>
                </div>
            </template>
        </div>
        <button @click.prevent="handleSave" :disabled="form.processing" class="btn btn-primary my-3"><span
                v-if="form.processing" class="spinner-border spinner-border-sm me-2"></span> Save
            Changes</button>
    </div>
</template>